#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: applications
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: #@ data.values.petclinic.image
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: applications
  labels:
    app: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
    - name: http
      protocol: TCP
      port: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: petclinic
  namespace: applications
spec:
  virtualhost:
    fqdn: petclinic.fender.lab.1t0chu.dev
    tls:
      secretName: petclinic-tls-secret
  routes:
    - services:
        - name: spring-petclinic
          port: 8080
